### ISSUE TITLE
[Task] Add Computed key to scaffold.yaml files

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/scaffold#11]
Add computed keys to scaffold.yaml file that can be computed with a template

**Example**

```yaml
questions:
  - name: "role_name"
    prompt:
      message: "Name of the Role"
    required: true
computed:
  role_name_snake: {{ snakecase .Scaffold.role_name }}
```

These would then be avaiable as 

```gotmpl
{{ .Computed.role_name_snake }}
```
