### ISSUE TITLE
feat: allow inject AFTER

### ISSUE THREAD

**Issue by anthonychung14** [hay-kot/scaffold#127]
wondered what your design thoughts were around making inject more flexible.

could be something as simple as
```
inject
 - name: "does thing"
    path: foo/bar
    after: "message BazDetails {"
```

**Comment by hay-kot** [comment]
I think that you could accomplish this already by adding a comment below that line? I generally prefer this because it's super clear that stuff is getting injected there.

I'm not opposed to the idea, though I think instead of 'after' we just have a mode property? That gives us some flexibility in the future if we needed to change something. 

```yaml
inject:
  - name: "add role to site.yaml"
    path: site.yaml
    mode: before # before | after
    at: "# $Scaffold.role_name"
    template: |
      - name: {{ .Scaffold.role_name }}
        role: {{ .Computed.snaked }}
```
