### ISSUE TITLE
computed properties not coerced to boolean in template engine?

### ISSUE THREAD

**Issue by alexeagle** [hay-kot/scaffold#130]
I ask a multi-prompt with some long options, so it's nice to use a computed property to reference the answer:

```
questions:
  - name: langs
    prompt:
      multi: true
      message: "Languages to be used in the project"
      options:
        - JavaScript & TypeScript
        - Python

computed:
  javascript: "{{ has \"JavaScript & TypeScript\" .Scaffold.langs }}"
  python: "{{ has \"Python\" .Scaffold.langs }}"
```

Inside the `scaffold.yaml` these seem to work:

```
features:
  - value: "{{ .Computed.python }}"
    globs:
      - "*/requirements*.txt"
```
only produces requirements.txt in the generated app as expected.

However these appear to be string-typed in the files themselves. Given a template

```
{{ .Computed }}
{{ .Computed.javascript }}
{{ .Computed.python }}

{{ if eq .Computed.python }}
case 1
{{ end }}
{{ if eq .Computed.python "true" }}
case 2
{{ end}}
```

The resulting application has
```
map[javascript:true python:false]
true
false


case 1
```
