### ISSUE TITLE
Extend Prompt Validation Support

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/scaffold#142]
Extend prompt/input validation to support additional options

Example:

```yaml
- name: prop1
  prompt: {}
  validate:
    required: true
    min: 10
    max: 20
    match: .*
```
