### ISSUE TITLE
[Task] support injectable templates

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/scaffold#15]
Add syntax for template type scaffolds for injectable snippets that can be inserted into existing files at a matching code line.

```yaml
inject:
  - name: Something for Debugging
    file: /path/to/router.go
    at: // $SCAFFOLD_INJECT <- User selectable matcher
    contents: |
        router.Get("/api/v1/{{ lower .Scaffold.resource }}", ctrl.Handle{{ title .Scaffold.resource }}Get)
        router.Post("/api/v1/{{ lower .Scaffold.resource }}", ctrl.Handle{{ title .Scaffold.resource }}Post)
```

When running the template it would do something like this

```go

func routes() {
    // ...other routes

    // $SCAFFOLD_INJECT 👇 
    router.Get("/api/v1/items", ctrl.HandleItemsGet)
    router.Post("/api/v1/items", ctrl.HandleItemsPost)

}
```

**Questions**

- Should we insert before or after the code comment. Should that be optionally set-able?
