### ISSUE TITLE
question: conditional template injection

### ISSUE THREAD

**Issue by anthonychung14** [hay-kot/scaffold#152]
I'd like to run an injection only if an input resolves to true. is there a way I can do this now?

**Comment by hay-kot** [comment]
I don't think this is explicitly supported, I think this would work if you did something like this?

```yaml
inject:
  - name: "add role to site.yaml"
    path: site.yaml
    at: "# $Scaffold.role_name"
    template: {{ if .Scaffold.some_value }} whatever thing you want {{ end }}
```

If that doesn't work, I can add this so that when the template evaluates to empty or whitespace we can ignore the inject.
