### ISSUE TITLE
[Task] Support conditional questions via template properties

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/scaffold#17]
Support conditional questions based on previous questions based on renderable templates that evaluate to boolean

```yaml
questions:
  - name: "ci_platform"
    prompt:
      message: "CI Platform"
      default: "MIT"
      options:
        - "github"
        - "drone.io"
        - "none"
  - name: "gh_username"
    prompt:
      message: "Github Username"
    when: "{{ eq .ci_platform "github" }} true {{ end }}"
```

Expression could likely be simplified, or we could add some utility functions to the template engine to make these expressions easier. 

Expression should evaluate to a strict "true" all other values are treated as false
