### ISSUE TITLE
Feature request: dynamic messages and default values

### ISSUE THREAD

**Issue by izeau** [hay-kot/scaffold#174]
**Description:**

It'd be awesome if we could use answers from previous questions in our question messages and default values.

**Current Limitations:**

Right now, all our prompts and defaults are static and can't adapt based on previous answers.

**Proposed Changes:**

1. **Dynamic Messages:**
   Let us use answers from earlier questions in new question prompts.
   ```yaml
   questions:
     - name: player_name
       required: true
       prompt:
         message: What's your name?

     - name: player_age
       required: true
       prompt:
         message: And how old are you, {{ .Scaffold.player_name }}?
   ```

2. **Dynamic Default Values:**
   Use previous answers to set default values with interpolations.
   ```yaml
   questions:
     - name: player_name
       required: true
       prompt:
         message: What's your name?

     - name: player_alias
       required: true
       prompt:
         message: Now, pick an alias
         default: |-
           {{ regexReplaceAll "[^a-z]+" (.Scaffold.player_name | lower) "_" }}
   ```

**Benefits:**

- **Better Experience:** More personalized and relevant questions.
- **Fewer Mistakes:** Auto-suggested values cut down on errors.
- **More Flexible:** Makes the questionnaire more adaptable.

What do you think?
