### ISSUE TITLE
[BUG] - Confirm doesn't show title only description

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/scaffold#212]
When using confirm, I shouldn't have to also provide a message for it to properly show up in the terminal UI

## Reproducible Example

```yaml
questions:
  - name: "enable_renovate"
    prompt:
      confirm: "Enable Renovate?"
      message: "Enable Renovate?"
      description: "Automatically update dependencies, via Renovate"
```
